kind: FreeFlowPolicySequence
apiVersion: api.ibm.com/v1
metadata:
  name: DPNano_PolicySequence
  namespace: DPNano_Product_MultiAPI
  version: '1'
  tags: []
  labels:
    gatewayTypes:
      - nano
spec:
  main:
    - $ref: DPNano_Product_MultiAPI:ExtractIdentity-c57me5:1
    - $ref: DPNano_Product_MultiAPI:Authenticate-eihle8:1
    - $ref: DPNano_Product_MultiAPI:Authorize-ybvnbr:1
    - $ref: DPNano_Product_MultiAPI:default-invoke-policy-weather-nano-seq:1
  monitoring:
    $ref: DPNano_Product_MultiAPI:DPNano_Telemetry:1.0
