kind: API
apiVersion: api.ibm.com/v1
metadata:
  name: WeatherApi_MultiApi
  namespace: DPv6_Product_MultiAPI
  version: '1.0'
  tags: []
  type: REST
spec:
  api-spec:
    $path: ./WeatherApi-spec.yml
  policy-sequence:
    - $ref: DPv6_Product_MultiAPI:DPv6_Assembly:1.0
