kind: CORS
apiVersion: api.ibm.com/v1
metadata:
  name: cors-proxy-api-test
  namespace: DPv5c_Product_Order-1
  version: 1.0.0
  tags: []
spec:
  rules:
    - action: allow
      originList:
        - '*'
      allowCredentials: false
      exposeHeaders:
        predefined: false
        custom: ''
        backend: false
