kind: Quota
apiVersion: api.ibm.com/v1
metadata:
  name: default-quota-1
  namespace: DPv5c_Product_Order-1
  version: 1.0.0
  description: ''
  tags: []
spec:
  maxRequest: 100
  interval: 1h
  extensions:
    dp-gateway:
      apiVersion: api.ibm.com/v1
      spec:
        onLimitReach: allow
